version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php-laravel
    volumes:
      - ./src:/var/www/html
    extra_hosts:
        - "host.docker.internal:host-gateway"
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: nginx-laravel
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: mysql-laravel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
